const dummyData = JSON.parse(`[{
    "id": 1,
    "first_name": "Gibby",
    "last_name": "Sannes",
    "email": "gsannes0@lycos.com",
    "gender": "Male"
  }, {
    "id": 2,
    "first_name": "Lissy",
    "last_name": "Luckes",
    "email": "lluckes1@stumbleupon.com",
    "gender": "Female"
  }, {
    "id": 3,
    "first_name": "Benedicto",
    "last_name": "Copplestone",
    "email": "bcopplestone2@xinhuanet.com",
    "gender": "Agender"
  }, {
    "id": 4,
    "first_name": "Fluke",
    "last_name": "Jirayu",
    "email": "asmuusloos@uusmoosgress.com",
    "gender": "Male"
  }, {
    "id": 5,
    "first_name": "Garv",
    "last_name": "MacCaughey",
    "email": "gmaccaughey4@gnu.org",
    "gender": "Male"
  }, {
    "id": 6,
    "first_name": "Martina",
    "last_name": "Siggin",
    "email": "msiggin5@ucsd.edu",
    "gender": "Female"
  }, {
    "id": 7,
    "first_name": "Mac",
    "last_name": "Sakarn",
    "email": "mac@ta.com",
    "gender": "Male"
  }, {
    "id": 8,
    "first_name": "Zacharie",
    "last_name": "McElory",
    "email": "zmcelory7@addtoany.com",
    "gender": "Non-binary"
  }, {
    "id": 9,
    "first_name": "Bjorn",
    "last_name": "Krzyzanowski",
    "email": "bkrzyzanowski8@apple.com",
    "gender": "Bigender"
  }, {
    "id": 10,
    "first_name": "Jim",
    "last_name": "Robo",
    "email": "Jim@Robo.com",
    "gender": "Genderfluid"
  }]`);
